# Generated by Django 3.1.7 on 2021-04-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firs_tname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_tname',
            new_name='last_name',
        ),
    ]
