# Generated by Django 3.1.7 on 2021-04-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210402_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_need',
            field=models.CharField(default='car', max_length=100),
        ),
    ]
