# Generated by Django 3.1.7 on 2021-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('SD', 'South Dakota'), ('IA', 'Iowa'), ('TX', 'Texas'), ('MD', 'Maryland'), ('VA', 'Virginia'), ('GA', 'Georgia'), ('RI', 'Rhode Island'), ('LA', 'Louisiana'), ('ID', 'Idaho'), ('ME', 'Maine'), ('OH', 'Ohio'), ('WA', 'Washington'), ('WY', 'Wyoming'), ('DE', 'Delaware'), ('HI', 'Hawaii'), ('MA', 'Massachusetts'), ('NC', 'North Carolina'), ('PA', 'Pennsylvania'), ('KY', 'Kentucky'), ('CO', 'Colorado'), ('OR', 'Oregon'), ('SC', 'South Carolina'), ('CT', 'Connecticut'), ('AK', 'Alaska'), ('KS', 'Kansas'), ('MO', 'Missouri'), ('AZ', 'Arizona'), ('VT', 'Vermont'), ('MT', 'Montana'), ('IN', 'Indiana'), ('MN', 'Minnesota'), ('OK', 'Oklahoma'), ('IL', 'Illinois'), ('NE', 'Nebraska'), ('WI', 'Wisconsin'), ('AR', 'Arkansas'), ('NY', 'New York'), ('NH', 'New Hampshire'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('DC', 'District Of Columbia'), ('UT', 'Utah'), ('WV', 'West Virginia'), ('TN', 'Tennessee'), ('NV', 'Nevada'), ('CA', 'California'), ('NM', 'New Mexico'), ('ND', 'North Dakota'), ('MS', 'Mississippi'), ('FL', 'Florida'), ('AL', 'Alabama')], max_length=100),
        ),
    ]
