# Generated by Django 3.1.7 on 2021-03-31 04:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210331_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('MT', 'Montana'), ('CA', 'California'), ('WV', 'West Virginia'), ('VT', 'Vermont'), ('DE', 'Delaware'), ('LA', 'Louisiana'), ('NH', 'New Hampshire'), ('NM', 'New Mexico'), ('MA', 'Massachusetts'), ('OH', 'Ohio'), ('TN', 'Tennessee'), ('MS', 'Mississippi'), ('VA', 'Virginia'), ('MO', 'Missouri'), ('AZ', 'Arizona'), ('CT', 'Connecticut'), ('MD', 'Maryland'), ('MI', 'Michigan'), ('SD', 'South Dakota'), ('NE', 'Nebraska'), ('AL', 'Alabama'), ('HI', 'Hawaii'), ('AR', 'Arkansas'), ('GA', 'Georgia'), ('NY', 'New York'), ('MN', 'Minnesota'), ('ME', 'Maine'), ('PA', 'Pennsylvania'), ('SC', 'South Carolina'), ('WA', 'Washington'), ('NJ', 'New Jersey'), ('IN', 'Indiana'), ('OR', 'Oregon'), ('NC', 'North Carolina'), ('NV', 'Nevada'), ('UT', 'Utah'), ('CO', 'Colorado'), ('OK', 'Oklahoma'), ('AK', 'Alaska'), ('FL', 'Florida'), ('TX', 'Texas'), ('DC', 'District Of Columbia'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('ND', 'North Dakota'), ('KY', 'Kentucky'), ('KS', 'Kansas'), ('WY', 'Wyoming'), ('IL', 'Illinois'), ('WI', 'Wisconsin'), ('RI', 'Rhode Island')], max_length=100),
        ),
    ]
