# Generated by Django 3.1.7 on 2021-03-31 04:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210331_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('KS', 'Kansas'), ('DE', 'Delaware'), ('RI', 'Rhode Island'), ('ME', 'Maine'), ('OK', 'Oklahoma'), ('ND', 'North Dakota'), ('WV', 'West Virginia'), ('LA', 'Louisiana'), ('MD', 'Maryland'), ('WA', 'Washington'), ('AL', 'Alabama'), ('MI', 'Michigan'), ('MS', 'Mississippi'), ('VT', 'Vermont'), ('MN', 'Minnesota'), ('NM', 'New Mexico'), ('MA', 'Massachusetts'), ('GA', 'Georgia'), ('KY', 'Kentucky'), ('NE', 'Nebraska'), ('IL', 'Illinois'), ('TN', 'Tennessee'), ('DC', 'District Of Columbia'), ('NC', 'North Carolina'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('PA', 'Pennsylvania'), ('CT', 'Connecticut'), ('IA', 'Iowa'), ('HI', 'Hawaii'), ('AK', 'Alaska'), ('WI', 'Wisconsin'), ('CA', 'California'), ('MO', 'Missouri'), ('WY', 'Wyoming'), ('UT', 'Utah'), ('VA', 'Virginia'), ('MT', 'Montana'), ('AR', 'Arkansas'), ('NY', 'New York'), ('NV', 'Nevada'), ('TX', 'Texas'), ('OH', 'Ohio'), ('CO', 'Colorado'), ('OR', 'Oregon'), ('AZ', 'Arizona'), ('FL', 'Florida'), ('ID', 'Idaho'), ('NJ', 'New Jersey'), ('IN', 'Indiana'), ('NH', 'New Hampshire')], max_length=100),
        ),
    ]
