# Generated by Django 3.1.7 on 2021-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210331_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AR', 'Arkansas'), ('VA', 'Virginia'), ('NM', 'New Mexico'), ('TX', 'Texas'), ('GA', 'Georgia'), ('NY', 'New York'), ('OR', 'Oregon'), ('ME', 'Maine'), ('MN', 'Minnesota'), ('AK', 'Alaska'), ('HI', 'Hawaii'), ('ND', 'North Dakota'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('MT', 'Montana'), ('DE', 'Delaware'), ('WA', 'Washington'), ('KS', 'Kansas'), ('MI', 'Michigan'), ('MS', 'Mississippi'), ('FL', 'Florida'), ('MO', 'Missouri'), ('IA', 'Iowa'), ('IL', 'Illinois'), ('WV', 'West Virginia'), ('NE', 'Nebraska'), ('CO', 'Colorado'), ('KY', 'Kentucky'), ('NV', 'Nevada'), ('RI', 'Rhode Island'), ('CA', 'California'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('SD', 'South Dakota'), ('AZ', 'Arizona'), ('NC', 'North Carolina'), ('NJ', 'New Jersey'), ('CT', 'Connecticut'), ('IN', 'Indiana'), ('AL', 'Alabama'), ('NH', 'New Hampshire'), ('UT', 'Utah'), ('MA', 'Massachusetts'), ('TN', 'Tennessee'), ('MD', 'Maryland'), ('PA', 'Pennsylvania'), ('DC', 'District Of Columbia'), ('LA', 'Louisiana'), ('SC', 'South Carolina'), ('ID', 'Idaho'), ('VT', 'Vermont')], max_length=100),
        ),
    ]
