# Generated by Django 3.1.7 on 2021-03-31 10:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210331_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('ND', 'North Dakota'), ('NH', 'New Hampshire'), ('LA', 'Louisiana'), ('AZ', 'Arizona'), ('MO', 'Missouri'), ('TN', 'Tennessee'), ('ID', 'Idaho'), ('GA', 'Georgia'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('DE', 'Delaware'), ('CT', 'Connecticut'), ('IA', 'Iowa'), ('AR', 'Arkansas'), ('NC', 'North Carolina'), ('UT', 'Utah'), ('CO', 'Colorado'), ('WV', 'West Virginia'), ('MS', 'Mississippi'), ('TX', 'Texas'), ('IL', 'Illinois'), ('OH', 'Ohio'), ('KS', 'Kansas'), ('NJ', 'New Jersey'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('KY', 'Kentucky'), ('NY', 'New York'), ('CA', 'California'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('HI', 'Hawaii'), ('NM', 'New Mexico'), ('RI', 'Rhode Island'), ('AK', 'Alaska'), ('SC', 'South Carolina'), ('MD', 'Maryland'), ('MT', 'Montana'), ('MI', 'Michigan'), ('MA', 'Massachusetts'), ('AL', 'Alabama'), ('WY', 'Wyoming'), ('SD', 'South Dakota'), ('ME', 'Maine'), ('MN', 'Minnesota'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('PA', 'Pennsylvania'), ('IN', 'Indiana')], max_length=100),
        ),
    ]
