# Generated by Django 3.1.7 on 2021-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210331_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('MN', 'Minnesota'), ('NY', 'New York'), ('NC', 'North Carolina'), ('TX', 'Texas'), ('UT', 'Utah'), ('MT', 'Montana'), ('IA', 'Iowa'), ('MI', 'Michigan'), ('AL', 'Alabama'), ('CT', 'Connecticut'), ('RI', 'Rhode Island'), ('VT', 'Vermont'), ('HI', 'Hawaii'), ('IN', 'Indiana'), ('MO', 'Missouri'), ('SC', 'South Carolina'), ('WA', 'Washington'), ('KY', 'Kentucky'), ('OH', 'Ohio'), ('MS', 'Mississippi'), ('ME', 'Maine'), ('CO', 'Colorado'), ('NJ', 'New Jersey'), ('DE', 'Delaware'), ('AZ', 'Arizona'), ('MD', 'Maryland'), ('AR', 'Arkansas'), ('WV', 'West Virginia'), ('NH', 'New Hampshire'), ('IL', 'Illinois'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('DC', 'District Of Columbia'), ('OK', 'Oklahoma'), ('SD', 'South Dakota'), ('GA', 'Georgia'), ('WY', 'Wyoming'), ('FL', 'Florida'), ('WI', 'Wisconsin'), ('VA', 'Virginia'), ('CA', 'California'), ('AK', 'Alaska'), ('NE', 'Nebraska'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('ND', 'North Dakota'), ('KS', 'Kansas'), ('OR', 'Oregon'), ('ID', 'Idaho')], max_length=100),
        ),
    ]
