# Generated by Django 3.1.7 on 2021-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210331_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('TR', 'Tripura'), ('KL', 'Kerala'), ('NL', 'Nagaland'), ('CH', 'Chandigarh'), ('RJ', 'Rajasthan'), ('HR', 'Haryana'), ('PB', 'Punjab'), ('WB', 'West Bengal'), ('JK', 'Jammu and Kashmir'), ('AS', 'Assam'), ('UK', 'Uttarakhand'), ('HP', 'Himachal Pradesh'), ('DD', 'Dadra and Nagar Haveli and Daman and Diu'), ('SK', 'Sikkim'), ('BR', 'Bihar'), ('JH', 'Jharkhand'), ('LD', 'Lakshadweep'), ('TS', 'Telangana'), ('AN', 'Andaman and Nicobar Islands'), ('TN', 'Tamil Nadu'), ('AR', 'Arunachal Pradesh'), ('OD', 'Odisha'), ('MH', 'Maharashtra'), ('MZ', 'Mizoram'), ('KA', 'Karnataka'), ('PY', 'Puducherry'), ('GJ', 'Gujarat'), ('DL', 'Delhi'), ('CG', 'Chhattisgarh'), ('LA', 'Ladakhk'), ('ML', 'Meghalaya'), ('MP', 'Madhya Pradesh'), ('GA', 'Goa'), ('AP', 'Andhra Pradesh'), ('UP', 'Uttar Pradesh')], max_length=100),
        ),
    ]
