# Generated by Django 3.1.7 on 2021-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210402_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('UK', 'Uttarakhand'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('CG', 'Chhattisgarh'), ('DL', 'Delhi'), ('PY', 'Puducherry'), ('LA', 'Ladakhk'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('PB', 'Punjab'), ('BR', 'Bihar'), ('DD', 'Dadra and Nagar Haveli and Daman and Diu'), ('MP', 'Madhya Pradesh'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('JK', 'Jammu and Kashmir'), ('LD', 'Lakshadweep'), ('SK', 'Sikkim'), ('HP', 'Himachal Pradesh'), ('GJ', 'Gujarat'), ('WB', 'West Bengal'), ('AR', 'Arunachal Pradesh'), ('TS', 'Telangana'), ('AN', 'Andaman and Nicobar Islands'), ('AS', 'Assam'), ('JH', 'Jharkhand'), ('AP', 'Andhra Pradesh'), ('NL', 'Nagaland'), ('GA', 'Goa'), ('OD', 'Odisha'), ('HR', 'Haryana'), ('CH', 'Chandigarh'), ('MH', 'Maharashtra'), ('MZ', 'Mizoram')], max_length=100),
        ),
    ]
