# Generated by Django 3.1.7 on 2021-04-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20210402_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('DL', 'Delhi'), ('CG', 'Chhattisgarh'), ('TS', 'Telangana'), ('OD', 'Odisha'), ('AR', 'Arunachal Pradesh'), ('BR', 'Bihar'), ('MZ', 'Mizoram'), ('AN', 'Andaman and Nicobar Islands'), ('MP', 'Madhya Pradesh'), ('PB', 'Punjab'), ('SK', 'Sikkim'), ('GA', 'Goa'), ('TR', 'Tripura'), ('DD', 'Dadra and Nagar Haveli and Daman and Diu'), ('AP', 'Andhra Pradesh'), ('UP', 'Uttar Pradesh'), ('KA', 'Karnataka'), ('HR', 'Haryana'), ('LA', 'Ladakhk'), ('KL', 'Kerala'), ('RJ', 'Rajasthan'), ('HP', 'Himachal Pradesh'), ('PY', 'Puducherry'), ('JK', 'Jammu and Kashmir'), ('MH', 'Maharashtra'), ('ML', 'Meghalaya'), ('CH', 'Chandigarh'), ('TN', 'Tamil Nadu'), ('GJ', 'Gujarat'), ('AS', 'Assam'), ('UK', 'Uttarakhand'), ('LD', 'Lakshadweep'), ('NL', 'Nagaland'), ('WB', 'West Bengal'), ('JH', 'Jharkhand')], max_length=100),
        ),
    ]
